osx_image: xcode7
language: objective-c
xcode_project: Reachability.xcodeproj
xcode_scheme: Reachability
notifications:
  email: false
script:
    - xcodebuild test -project Reachability.xcodeproj -scheme Reachability -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO
notifications:
  slack: willowtree:s24dVJQRoR4HJGUmeG0YCsZv
